import { readFile } from "node:fs/promises";
import path from "node:path";
import config from "@/explore-ai.config.json";
import { buildCatalogRoutes, type CatalogEntry } from "../.agents/skills/explore-ai/assets/templates/CatalogRoutes";

export { catalogLessonRoute } from "../.agents/skills/explore-ai/assets/templates/CatalogRoutes";

// Generated by the installed builder from actual lesson files; no parallel catalog model.
export async function getCatalog() {
  const catalog: { entries: CatalogEntry[] } = JSON.parse(await readFile(path.join(process.cwd(), config.paths.catalog), "utf8"));
  return { entries: catalog.entries, ...buildCatalogRoutes(catalog.entries) };
}

export function displayKey(key: string) {
  return key.replaceAll("-", " ");
}
